//! Pure logic layer — no `#[update]`/`#[query]` attributes here.
//!
//! These functions are the programmatic API for library consumers.
//! Candid endpoint wrappers are generated by `export_hnsw!()` in `lib.rs`.

use candid::Principal;
use ic_cdk::caller;

use crate::{
    error::{HnswError, Result},
    hnsw::dist_fn,
    storage::{
        StoredCollection,
        collection_exists_by_name, get_collection, get_node,
        get_controller_only, set_controller_only as set_controller_only_flag,
        next_collection_id, put_collection, put_node,
        remove_all_nodes, remove_collection, remove_node,
    },
    types::{
        AccessEntry, CollectionConfig, CollectionId, CollectionInfo,
        InsertRequest, NodeId, Role, SearchRequest, SearchResult,
    },
};

// ── Helpers ───────────────────────────────────────────────────────────────────

pub(crate) fn require_role(coll: &StoredCollection, min_role: Role) -> Result<()> {
    let c = caller();
    // Canister controllers always have implicit Owner access, regardless of mode.
    if ic_cdk::api::is_controller(&c) {
        return Ok(());
    }
    // When the controller-only gate is on, no one else may call.
    if get_controller_only() {
        return Err(HnswError::Unauthorized);
    }
    // Normal collection-level role check.
    match coll.role_of(&c) {
        Some(Role::Owner)  => Ok(()),
        Some(Role::Writer) if min_role != Role::Owner => Ok(()),
        Some(Role::Reader) if min_role == Role::Reader => Ok(()),
        _ => Err(HnswError::Unauthorized),
    }
}

/// Check the canister-level gate for operations that have no collection yet
/// (e.g. `create_collection`).
pub(crate) fn check_gate() -> Result<()> {
    let c = caller();
    if ic_cdk::api::is_controller(&c) {
        return Ok(());
    }
    if get_controller_only() {
        return Err(HnswError::Unauthorized);
    }
    Ok(())
}

pub(crate) fn load_collection(id: CollectionId) -> Result<StoredCollection> {
    get_collection(id).ok_or(HnswError::CollectionNotFound(id))
}

// ── Canister-level gate ───────────────────────────────────────────────────────

/// Enable or disable the controller-only access gate. Controller only.
///
/// When enabled every non-controller caller receives `Unauthorized`, regardless
/// of their collection role. Canister controllers always retain implicit Owner
/// access even when the gate is off.
///
/// The setting is stored in stable memory and survives canister upgrades.
pub fn set_controller_only(enabled: bool) -> Result<()> {
    if !ic_cdk::api::is_controller(&caller()) {
        return Err(HnswError::Unauthorized);
    }
    set_controller_only_flag(enabled);
    Ok(())
}

/// Query whether the controller-only gate is currently active.
pub fn get_controller_only_setting() -> bool {
    get_controller_only()
}

// ── Collection management ─────────────────────────────────────────────────────

pub fn create_collection(config: CollectionConfig) -> Result<CollectionId> {
    check_gate()?;
    if config.m < 2 || config.m > 64 {
        return Err(HnswError::InvalidConfig("m must be 2..=64".into()));
    }
    if (config.ef_construction as u8) < config.m {
        return Err(HnswError::InvalidConfig(
            "ef_construction must be >= m".into(),
        ));
    }
    if collection_exists_by_name(&config.name) {
        return Err(HnswError::CollectionAlreadyExists);
    }

    let id       = next_collection_id();
    let distance = match config.distance {
        crate::types::DistanceMetric::Cosine     => 0,
        crate::types::DistanceMetric::Euclidean  => 1,
        crate::types::DistanceMetric::DotProduct => 2,
    };

    put_collection(id, StoredCollection {
        name:            config.name,
        dim:             config.dim,
        m:               config.m,
        m_max0:          config.m * 2,
        ef_construction: config.ef_construction,
        distance,
        entry_point:     None,
        max_layer:       0,
        next_node_id:    0,
        node_count:      0,
        rng_state:       ic_cdk::api::time(),
        owner:           caller(),
        writers:         vec![],
        readers:         vec![],
    });

    Ok(id)
}

pub fn delete_collection(id: CollectionId) -> Result<()> {
    let coll = load_collection(id)?;
    require_role(&coll, Role::Owner)?;
    remove_all_nodes(id);
    remove_collection(id);
    Ok(())
}

pub fn collection_info(id: CollectionId) -> Result<CollectionInfo> {
    let coll = load_collection(id)?;
    require_role(&coll, Role::Reader)?;
    let distance = coll.distance_metric();
    Ok(CollectionInfo {
        id,
        name:            coll.name,
        dim:             coll.dim,
        m:               coll.m,
        ef_construction: coll.ef_construction,
        distance,
        node_count:      coll.node_count,
        max_layer:       coll.max_layer,
        owner:           coll.owner,
    })
}

// ── Access control ────────────────────────────────────────────────────────────

pub fn grant_access(
    collection_id: CollectionId,
    principal:     Principal,
    role:          Role,
) -> Result<()> {
    let mut coll = load_collection(collection_id)?;
    require_role(&coll, Role::Owner)?;

    if principal == coll.owner {
        return Err(HnswError::InvalidConfig(
            "cannot change owner's role".into(),
        ));
    }

    coll.writers.retain(|p| p != &principal);
    coll.readers.retain(|p| p != &principal);

    match role {
        Role::Owner  => return Err(HnswError::InvalidConfig(
            "use transfer_ownership to change the owner".into(),
        )),
        Role::Writer => coll.writers.push(principal),
        Role::Reader => coll.readers.push(principal),
    }

    put_collection(collection_id, coll);
    Ok(())
}

pub fn revoke_access(collection_id: CollectionId, principal: Principal) -> Result<()> {
    let mut coll = load_collection(collection_id)?;
    require_role(&coll, Role::Owner)?;
    coll.writers.retain(|p| p != &principal);
    coll.readers.retain(|p| p != &principal);
    put_collection(collection_id, coll);
    Ok(())
}

pub fn list_access(collection_id: CollectionId) -> Result<Vec<AccessEntry>> {
    let coll = load_collection(collection_id)?;
    require_role(&coll, Role::Owner)?;

    let mut entries = vec![AccessEntry { principal: coll.owner, role: Role::Owner }];
    entries.extend(coll.writers.iter().map(|&p| AccessEntry { principal: p, role: Role::Writer }));
    entries.extend(coll.readers.iter().map(|&p| AccessEntry { principal: p, role: Role::Reader }));
    Ok(entries)
}

pub fn transfer_ownership(
    collection_id: CollectionId,
    new_owner:     Principal,
) -> Result<()> {
    let mut coll = load_collection(collection_id)?;
    require_role(&coll, Role::Owner)?;
    coll.writers.push(coll.owner);
    coll.writers.retain(|p| p != &new_owner);
    coll.readers.retain(|p| p != &new_owner);
    coll.owner = new_owner;
    put_collection(collection_id, coll);
    Ok(())
}

// ── Vector operations ─────────────────────────────────────────────────────────

pub fn insert(req: InsertRequest) -> Result<NodeId> {
    let mut coll = load_collection(req.collection_id)?;
    require_role(&coll, Role::Writer)?;

    if req.vector.len() as u32 != coll.dim {
        return Err(HnswError::DimensionMismatch {
            expected: coll.dim,
            got:      req.vector.len() as u32,
        });
    }

    let node_id = coll.next_node_id;
    let metric  = coll.distance_metric();

    let result = crate::hnsw::insert(
        req.collection_id,
        node_id,
        req.vector,
        req.metadata,
        coll.entry_point,
        coll.max_layer,
        coll.m,
        coll.m_max0,
        coll.ef_construction,
        dist_fn(&metric),
        &mut coll.rng_state,
    );

    if let Some(ep) = result.new_entry_point {
        coll.entry_point = Some(ep);
    }
    coll.max_layer    = result.new_max_layer;
    coll.next_node_id += 1;
    coll.node_count   += 1;
    put_collection(req.collection_id, coll);

    Ok(node_id)
}

pub fn delete_node(collection_id: CollectionId, node_id: NodeId) -> Result<()> {
    let mut coll = load_collection(collection_id)?;
    require_role(&coll, Role::Writer)?;

    if get_node(collection_id, node_id).is_none() {
        return Err(HnswError::NodeNotFound(node_id));
    }

    if let Some(node) = get_node(collection_id, node_id) {
        for (layer, neighbours) in node.layers.iter().enumerate() {
            for &n_id in neighbours {
                if let Some(mut n_node) = get_node(collection_id, n_id) {
                    if let Some(list) = n_node.layers.get_mut(layer) {
                        list.retain(|&id| id != node_id);
                    }
                    put_node(collection_id, n_id, n_node);
                }
            }
        }
    }

    remove_node(collection_id, node_id);
    coll.node_count = coll.node_count.saturating_sub(1);

    if coll.entry_point == Some(node_id) {
        coll.entry_point = find_new_entry_point(collection_id);
    }

    put_collection(collection_id, coll);
    Ok(())
}

pub(crate) fn find_new_entry_point(collection_id: CollectionId) -> Option<NodeId> {
    use crate::storage::{NodeKey, NODES};
    NODES.with(|n| {
        n.borrow()
            .range(
                NodeKey::new(collection_id, 0)
                    ..=NodeKey::new(collection_id, u64::MAX),
            )
            .next()
            .map(|(k, _)| k.node_id)
    })
}

pub fn search(req: SearchRequest) -> Result<Vec<SearchResult>> {
    let coll = load_collection(req.collection_id)?;
    require_role(&coll, Role::Reader)?;

    if req.vector.len() as u32 != coll.dim {
        return Err(HnswError::DimensionMismatch {
            expected: coll.dim,
            got:      req.vector.len() as u32,
        });
    }
    if req.ef_search < req.top_k {
        return Err(HnswError::InvalidSearchParams);
    }

    let ep = match coll.entry_point {
        Some(ep) => ep,
        None     => return Ok(vec![]),
    };

    let metric = coll.distance_metric();
    let candidates = crate::hnsw::knn_search(
        req.collection_id,
        &req.vector,
        ep,
        coll.max_layer,
        req.top_k as usize,
        req.ef_search as usize,
        dist_fn(&metric),
    );

    Ok(candidates
        .into_iter()
        .filter_map(|c| {
            get_node(req.collection_id, c.id).map(|node| SearchResult {
                id:       c.id,
                distance: c.dist,
                metadata: node.metadata,
            })
        })
        .collect())
}
